spring:
  application:
    name: bakery
  web:
    cors:
      allowed-origins: "http://localhost:4200"

  datasource:
    url: jdbc:postgresql://localhost:5431/bakery
    username: admin
    password: sc
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  output:
    ansi:
      enabled: always

server:
  port: 8081
